[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }